### ISSUE TITLE
Documentation broken for nested controllers

### ISSUE THREAD

**Issue by johanneswuerbach** [Apipie/apipie-rails#104]
I have some nested controllers in my app:

``` ruby
namespace :users do
  resource :sessions, only: [:create, :destroy]
end
namespace :sellers do
  resource :sessions, only: [:create, :destroy]
end
```

The documentation of those controllers is generated as Sessions and the Sellers::SessionsController documentation is overwriting the Users::SessionsController documentation. I added resource_ids for both controllers, this displays both documentations, but the examples are still recorded as sessions#create and not displayed.

**Comment by erlandsona** [comment]
@iNecas I'm trying to I have routes that look like...
routes.rb -- edited slightly...
```
  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  namespace :api, path: '/', defaults: {format: :json} do
    # constraints subdomain: 'api' do
      scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
        resources :brands, only: [:index, :show, :create, :update, :destroy], concerns: :paginatable do
          resources :models, only: [:index, :create], concerns: :paginatable, controller: 'brands/models' do
            resources :sub_models, only: [:index, :create], path: 'sub-models', concerns: :paginatable, controller: 'brands/models/sub_models'
          end
          resources :sub_models, only: [:index], path: 'sub-models', concerns: :paginatable, controller: 'brands/sub_models'
        end
        resources :models, only: [:index, :show, :create, :update, :destroy], concerns: :paginatable do
          resources :brands, only: [:index, :create], concerns: :paginatable, controller: 'models/brands'
          resources :sub_models, only: [:index, :create], path: 'sub-models', concerns: :paginatable, controller: 'models/sub_models'
        end
        resources :sub_models, path: 'sub-models', only: [:index, :show, :create, :update, :destroy], concerns: :paginatable do
          resources :brands, only: [:index], concerns: :paginatable, controller: 'sub_models/brands'
          resources :models, only: [:index, :create], concerns: :paginatable, controller: 'sub_models/models'
        end
      end
    # end
  end
```

Currently my docs are duplicating the top level Name for whatever resource they are accessing... EG: There are Three H1 Brands and three H1 Models each with the corresponding routes but it would be nice if all of the routes for the CRUD operations on each model where defined under a single H1 for Brands.

EG:

What it is...

Brands
 - GET /brands 'list brands'
 - GET /brands(/page/:page) 'list brands'
 - GET /brands/:id 'show a brand'
 - etc... for other CRUD's
Brands
 - GET /models/:id/brands 'list brands of a particular model'
 - etc...

Brands
 - GET /sub-models/:id/brands 'list brands of a particular Sub Model'

Models
 - etc...
Models
 - etc...
Models
 - etc...


__What I would like__

Brands
 - GET /brands 'list brands'
 - GET /models/:id/brands 'list brands of a particular model'
 - GET /sub-models/:id/brands 'list brands of a particular sub-model'
 - etc...
Models
 - GET /models 'list models'
 - GET /brands/:id/models 'list models of a particular brand'
 - GET /sub-models/:id/models 'list models of a particular sub-model'

Etc...

Am I missing something that's already documented or is this just tricky to do?

**Comment by itskingori** [comment]
See fix in https://github.com/Apipie/apipie-rails/issues/455#issuecomment-268555114.
