### ISSUE TITLE
generator.rb - dead code?

### ISSUE THREAD

**Issue by voxik** [Apipie/apipie-rails#135]
`https://github.com/Pajk/apipie-rails/blob/master/lib/apipie/client/generator.rb` seems to be dead code. It references another files, which are not available in repository: `https://github.com/Pajk/apipie-rails/blob/master/lib/apipie/client/generator.rb#L8`

Also note that the `generator.rb` uses `/bin/env` shebang, which might be issue for Fedora, that's where came my interest in this file ;)

[1] https://lists.fedoraproject.org/pipermail/devel/2013-July/185797.html

**Comment by voxik** [comment]
ping

Any update? I think I am going to drop the file from Fedora for the moment, since I was asked if I can change the shebang ...

**Comment by iNecas** [comment]
Yes, this is a dead code we can remove
