### ISSUE TITLE
Protect doc with HTTP basic auth

### ISSUE THREAD

**Issue by julien-duponchelle** [Apipie/apipie-rails#138]
It can be usefull to have an example or a way to enable HTTP basic auth on the documentation.

**Comment by dminchev** [comment]
+1

**Comment by nicholasjon** [comment]
+1

**Comment by saneshark** [comment]
isn't it just a matter of creating a controller with the same namespace the gem uses and adding in whatever before actions you use for authentication elsewhere in your project?
