### ISSUE TITLE
Layout is off center

### ISSUE THREAD

**Issue by barmstrong** [Apipie/apipie-rails#142]
The number of pixels on the left/right side of the layout is different due to the how the 'row' class is being used.

(It's more apparent if you put something in the footer and it is misaligned with the main container content).

This is what I did my branch if you want to cherry pick a commit: https://github.com/barmstrong/apipie-rails/commit/2dcc49612e22e05c438a1762320501f7b5ee6d62

Thanks!

**Comment by Pajk** [comment]
At this point fluid layout is used so this should be no longer an issue as the container uses page's full width.
