### ISSUE TITLE
Controllers with the same name in different modules/namespaces

### ISSUE THREAD

**Issue by vkinelev** [Apipie/apipie-rails#233]
I have UsersController in the "app" & "admin" namespaces, but Apipie shows docs from one controller only.

The workaround is to set explicitly a different "resource_id" for every controller, but in this case they are not grouped together.

**Comment by zuzana-dostalova-merck-com** [comment]
I am having the same issue and it is still not working. When I set the `config.namespaced_resources` to true, I got an error: 
```
NoMethodError in Apipie::ApipiesController#index
undefined method `+' for nil:NilClass
```
Did I need to do anything else in order for it to work?

**Comment by milj** [comment]
I'm experiencing the same issue. The problem lies in `lib/apipie/application.rb:396` in `version_prefix`
