### ISSUE TITLE
Rails 3.0.x: undefined method *heading*, issue with ActionDispatch::Reloader

### ISSUE THREAD

**Issue by jensb** [Apipie/apipie-rails#251]
Using Rails 3.0.20 and Ruby 1.9.3, I get this error when trying to access the apipie index:

*NoMethodError in Apipie/apipies#index*

Showing .../ruby1.9/gems/1.9.1/gems/apipie-rails-0.1.3/app/views/apipie/apipies/_method_detail.erb where line #34 raised:

*undefined method `heading' for #<#<Class:0x007fabe6e27770>:0x007fabe6ddc658>*
Extracted source (around line #34):

    31: <% end %>
    32: 
    33: <% unless method[:params].blank? %>
    34:   <%= heading('Params', h_level) %>
    35:   <table class='table'>
    36:     <thead>
    37:       <tr>

If this is Rails-3.0 specific: I know that Rails 3.0 is deprecated, but if a fix is trivial (it's in a template, after all), can you provide a patch? 
Thank you!

**Comment by saneshark** [comment]
:bug: This is an issue on:  `rails (4.0.12)` and `ruby 2.1.5`

**Comment by saneshark** [comment]
This fixed the issue for my project, but I'm wondering if maybe it is a bad idea to have heading in a Helper altogether, as the same method name could be implemented for a given project and would simply override the method defined here as the method call is not namespaced from what I can tell. 

It would be better to get rid of `ApipieHelper` altogether and add it in to the controller with 

```ruby
  def heading(title, level=1)
    content_tag("h#{level}") do
      title
    end
  end
  helper_method :heading
```

This way the method defined within the project could be overridden at the controller level. Attempting this resulted in 5 failed tests however.

**Comment by saneshark** [comment]
@iNecas this seems to have resolved the issue for my project.
