### ISSUE TITLE
undefined method `def_param_group' for Concern module

### ISSUE THREAD

**Issue by Morpheu5** [Apipie/apipie-rails#258]
Hello there. I have this Concern in my application, something like

```
module Authentication
    extend ActiveSupport::Concern

    def_param_group :credentials do
        param :username, String, :required => true
        param :password, String, :required => true
        param :timestamp, String, :required => true
    end
...
```

and when I run Apipie, I get the following

> undefined method `def_param_group' for Authentication:Module

whereas if I move the param group inside a controller, there's no problem with that. What exactly am I doing wrong? Otherwise, Apipie is great.

**Comment by acajic** [comment]
I'm getting that my param group is not defined. How do I specify the scope?
