### ISSUE TITLE
Can't Run Rspec Version 3 with api-pie doc file

### ISSUE THREAD

**Issue by eshaiju** [Apipie/apipie-rails#302]
while running rpsec got error like this 

/home/demo/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych.rb:298:in `load_file': wrong number of arguments (2 for 1) (ArgumentError)
	from /home/demo/.rvm/gems/ruby-2.0.0-p353/gems/apipie-rails-0.0.24/lib/apipie/application.rb:212:in `recorded_examples'
	from /home/demo/.rvm/gems/ruby-2.0.0-p353/gems/apipie-rails-0.0.24/lib/apipie/apipie_module.rb:18:in `method_missing'
	from /home/demo/.rvm/gems/ruby-2.0.0-p353/gems/apipie-rails-0.0.24/lib/apipie/method_description.rb:155:in `load_recorded_examples'
	from /home/demo/.rvm/gems/ruby-2.0.0-p353/gems/apipie-rails-0.0.24/lib/apipie/method_description.rb:42:in `initialize'
	from /home/demo/.rvm/gems/ruby-2.0.0-p353/gems/apipie-rails-0.0.24/lib/apipie/application.rb:46:in `new'
	from /home/demo/.rvm/gems/ruby-2.0.0-p353/gems/apipie-rails-0.0.24/lib/apipie/application.rb:46:in `block in define_method_description'
	from /home/demo/.rvm/gems/ruby-2.0.0-p353/gems/apipie-rails-0.0.24/lib/apipie/application.rb:38:in `each'
	from /home/demo/.rvm/gems/ruby-2.0.0-p353/gems/apipie-rails-0.0.24/lib/apipie/application.rb:38:in `define_method_description'
	from /home/demo/.rvm/gems/ruby-2.0.0-p353/gems/apipie-rails-0.0.24/lib/apipie/apipie_module.rb:18:in `method_missing'
	from /home/demo/.rvm/gems/ruby-2.0.0-p353/gems/apipie-rails-0.0.24/lib/apipie/dsl_definition.rb:318:in `method_added'
	from /home/demo/projects/demo-app/app/controllers/api/v1/feedbacks_controller.rb:20:in `<class:FeedbacksController>'
	from /home/demo/projects/demo-app/app/controllers/api/v1/feedbacks_controller.rb:1:in `<top (required)>'

gemfile lock

GIT
  remote: git://github.com/gregbell/active_admin.git
  revision: bf9dabe6a568f2e17a65c3310530cbba77dfce9c
  specs:
    activeadmin (1.0.0.pre)
      arbre (~> 1.0)
      bourbon
      coffee-rails
      formtastic (~> 2.3.0.rc3)
      inherited_resources (~> 1.4.1)
      jquery-rails
      jquery-ui-rails (~> 5.0)
      kaminari (~> 0.15)
      rails (>= 3.2, < 4.2)
      ransack (~> 1.0)
      sass-rails

GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.1.4)
      actionpack (= 4.1.4)
      actionview (= 4.1.4)
      mail (~> 2.5.4)
    actionpack (4.1.4)
      actionview (= 4.1.4)
      activesupport (= 4.1.4)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    actionview (4.1.4)
      activesupport (= 4.1.4)
      builder (~> 3.1)
      erubis (~> 2.7.0)
    activemodel (4.1.4)
      activesupport (= 4.1.4)
      builder (~> 3.1)
    activerecord (4.1.4)
      activemodel (= 4.1.4)
      activesupport (= 4.1.4)
      arel (~> 5.0.0)
    activesupport (4.1.4)
      i18n (~> 0.6, >= 0.6.9)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.1)
      tzinfo (~> 1.1)
    addressable (2.3.6)
    apipie-rails (0.0.24)
      rails (>= 3.0.10)
    arbre (1.0.1)
      activesupport (>= 3.0.0)
    arel (5.0.1.20140414130214)
    bcrypt (3.1.7)
    bourbon (3.2.3)
      sass (~> 3.2)
      thor
    builder (3.2.2)
    capistrano (2.15.5)
      highline
      net-scp (>= 1.0.0)
      net-sftp (>= 2.0.0)
      net-ssh (>= 2.0.14)
      net-ssh-gateway (>= 1.1.0)
    capistrano-ext (1.2.1)
      capistrano (>= 1.0.0)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cocaine (0.5.4)
      climate_control (>= 0.0.3, < 1.0)
    coffee-rails (4.0.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.3.0)
      coffee-script-source
      execjs
    coffee-script-source (1.7.1)
    crack (0.4.2)
      safe_yaml (~> 1.0.0)
    devise (3.2.4)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    diff-lcs (1.2.5)
    docile (1.1.5)
    erubis (2.7.0)
    execjs (2.2.1)
    factory_girl (4.4.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.4.1)
      factory_girl (~> 4.4.0)
      railties (>= 3.0.0)
    formtastic (2.3.0.rc3)
      actionpack (>= 3.0)
    haml (4.0.5)
      tilt
    haml-rails (0.5.3)
      actionpack (>= 4.0.1)
      activesupport (>= 4.0.1)
      haml (>= 3.1, < 5.0)
      railties (>= 4.0.1)
    has_scope (0.6.0.rc)
      actionpack (>= 3.2, < 5)
      activesupport (>= 3.2, < 5)
    highline (1.6.21)
    hike (1.2.3)
    i18n (0.6.11)
    inherited_resources (1.4.1)
      has_scope (~> 0.6.0.rc)
      responders (~> 1.0.0.rc)
    jbuilder (2.1.3)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jquery-rails (3.1.1)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery-turbolinks (2.0.2)
      railties (>= 3.1.0)
      turbolinks
    jquery-ui-rails (5.0.0)
      railties (>= 3.2.16)
    json (1.8.1)
    kaminari (0.16.1)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    libv8 (3.16.14.3)
    mail (2.5.4)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    mime-types (1.25.1)
    mini_portile (0.6.0)
    minitest (5.4.0)
    multi_json (1.10.1)
    mysql2 (0.3.16)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-sftp (2.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (2.9.1)
    net-ssh-gateway (1.2.0)
      net-ssh (>= 2.6.5)
    nokogiri (1.6.3.1)
      mini_portile (= 0.6.0)
    orm_adapter (0.5.0)
    paperclip (3.5.4)
      activemodel (>= 3.0.0)
      activesupport (>= 3.0.0)
      cocaine (~> 0.5.3)
      mime-types
    polyamorous (1.0.0)
      activerecord (>= 3.0)
    polyglot (0.3.5)
    rack (1.5.2)
    rack-test (0.6.2)
      rack (>= 1.0)
    rails (4.1.4)
      actionmailer (= 4.1.4)
      actionpack (= 4.1.4)
      actionview (= 4.1.4)
      activemodel (= 4.1.4)
      activerecord (= 4.1.4)
      activesupport (= 4.1.4)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.1.4)
      sprockets-rails (~> 2.0)
    railties (4.1.4)
      actionpack (= 4.1.4)
      activesupport (= 4.1.4)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.3.2)
    ransack (1.2.3)
      actionpack (>= 3.0)
      activerecord (>= 3.0)
      activesupport (>= 3.0)
      i18n
      polyamorous (~> 1.0.0)
    rdoc (4.1.1)
      json (~> 1.4)
    ref (1.0.5)
    responders (1.0.0)
      railties (>= 3.2, < 5)
    rspec-core (3.0.3)
      rspec-support (~> 3.0.0)
    rspec-expectations (3.0.3)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.0.0)
    rspec-mocks (3.0.3)
      rspec-support (~> 3.0.0)
    rspec-rails (3.0.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.0.0)
      rspec-expectations (~> 3.0.0)
      rspec-mocks (~> 3.0.0)
      rspec-support (~> 3.0.0)
    rspec-support (3.0.3)
    rvm-capistrano (1.5.3)
      capistrano (~> 2.15.4)
    safe_yaml (1.0.3)
    sass (3.2.19)
    sass-rails (4.0.3)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.2.0)
      sprockets (~> 2.8, <= 2.11.0)
      sprockets-rails (~> 2.0)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    shoulda (3.5.0)
      shoulda-context (~> 1.0, >= 1.0.1)
      shoulda-matchers (>= 1.4.1, < 3.0)
    shoulda-context (1.2.1)
    shoulda-matchers (2.6.2)
      activesupport (>= 3.0.0)
    simple_form (3.0.2)
      actionpack (~> 4.0)
      activemodel (~> 4.0)
    simplecov (0.9.0)
      docile (~> 1.1.0)
      multi_json
      simplecov-html (~> 0.8.0)
    simplecov-html (0.8.0)
    spork (1.0.0rc4)
    spring (1.1.3)
    sprockets (2.11.0)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.1.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (~> 2.8)
    therubyracer (0.12.1)
      libv8 (~> 3.16.14.0)
      ref
    thor (0.19.1)
    thread_safe (0.3.4)
    tilt (1.4.1)
    treetop (1.4.15)
      polyglot
      polyglot (>= 0.3.1)
    turbolinks (2.2.2)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.5.3)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    warden (1.2.3)
      rack (>= 1.0)
    webmock (1.11.0)
      addressable (>= 2.2.7)
      crack (>= 0.3.2)
    webrat (0.7.3)
      nokogiri (>= 1.2.0)
      rack (>= 1.0)
      rack-test (>= 0.5.3)

PLATFORMS
  ruby

DEPENDENCIES
  activeadmin!
  apipie-rails (~> 0.0.24)
  capistrano (~> 2.15.5)
  capistrano-ext
  coffee-rails (~> 4.0.0)
  devise (~> 3.2.0)
  factory_girl_rails
  haml (>= 3.0.0)
  haml-rails
  inherited_resources (~> 1.4.1)
  jbuilder (~> 2.0)
  jquery-rails
  jquery-turbolinks
  mysql2
  paperclip (~> 3.5.2)
  rails (= 4.1.4)
  ransack
  rspec-rails (~> 3.0.0)
  rvm-capistrano
  sass-rails (~> 4.0.3)
  sdoc (~> 0.4.0)
  shoulda
  shoulda-matchers
  simple_form (~> 3.0.0.rc)
  simplecov
  spork (~> 1.0rc)
  spring
  therubyracer
  turbolinks
  uglifier (>= 1.3.0)
  webmock (~> 1.11.0)
  webrat

**Comment by alan-andrade** [comment]
Should this be closed  @eshaiju  ?
