### ISSUE TITLE
api_base_url based on version

### ISSUE THREAD

**Issue by AvaelKross** [Apipie/apipie-rails#317]
I have this config:
```
config.default_version         = 'v1'
config.api_base_url            = "/api"
```
And I want to have generated paths like "/api/v1/...". Can't found a solution for this (must be) popular problem..

**Comment by wazery** [comment]
I myself use this:

`config.api_base_url = '/api/v1'`

I don't see a problem of specifying it this way.

**Comment by Pajk** [comment]
@AvaelKross You can have different api_base_url for each version.

When you use `config.api_base_url=` you are setting the base url for your default version and it's equivalent to:

    config.api_base_url["v1"] = "/api"

So what you can do is eg:

    config.api_base_url["v1"] = "/v1"
    config.api_base_url["v2"] = "/v2"

You can also specify base URL in a controller same way how it's done in our [dummy app](https://github.com/Apipie/apipie-rails/blob/master/spec/dummy/app/controllers/api/v1/base_controller.rb).
