### ISSUE TITLE
undefined method `api!' 

### ISSUE THREAD

**Issue by scottrobertson** [Apipie/apipie-rails#319]
Ruby: 2.1.5p273
Rails: 4.2.0
Gem: 0.2.6

![](https://s3.amazonaws.com/f.cl.ly/items/2h3s2R3K2i3D332F3p3o/Image%202015-01-02%20at%2012.58.55%20am.png)

**Comment by iNecas** [comment]
Hi, we have not released the new version just yet, but for now, so for now, you can point your dependency directly on the master: this is a brand-new feature and it's an opportunity for the feedback before it gets into the next release (which will be the 0.3.0)

**Comment by scottrobertson** [comment]
Oops sorry, I did not notice it was not released yet, my bad.
