### ISSUE TITLE
document response object

### ISSUE THREAD

**Issue by trungpham** [Apipie/apipie-rails#321]
is there a way to document the response object? it's just as important as the request object.

**Comment by iNecas** [comment]
Not yet but I would be happy to review a patch that would introduce that.

**Comment by iNecas** [comment]
Just noticed it's a duplicate of #273 Closing in favor of that request

**Comment by noctivityinc** [comment]
+1  We need some kind of way to document in a table what the various response elements mean.  Its great to have the example, but without an explaination of the response object it's harder to use the API.
