### ISSUE TITLE
Can it be write in a separate file?

### ISSUE THREAD

**Issue by jerry-tao** [Apipie/apipie-rails#336]
Can i write the doc in a separate file? Just like pundit policy files.

Like:

```ruby
#apipie/posts_api.rb
def index
  api :GET
end
```

**Comment by iNecas** [comment]
Hi. Not at the moment. Given the apipie is just another Ruby code, it might not be that hard to get there. Could you elaborate on your use-case or more complete example and what benefits it would have against the current status?

**Comment by jerry-tao** [comment]
Yes, i will consider to make a p/r when i have time.

The reason is the api doc has nothing to do with the logic, but it makes the controllers look fat.  

For example, if i want to remove the apipie totally i have to edit all my api controllers. It is not like comments, i can't just leave them there. So if all docs are in separate files. It will be easier.

**Comment by jerry-tao** [comment]
And more if i put them in plain objects, it will be easier for reusing the code. 

Like:

```ruby
class BaseApi
  def show
    error 404, "Missing"
  end 
end

class PostApi<BaseApi
  def show
    api :GET
    super
  end
end
```

**Comment by iNecas** [comment]
You might consider the concerts feature, that we already support.

**Comment by IlyaBylich** [comment]
@jerry-tao this gem uses `method_added` hook for collecting docs. this means that you can make a separated module and define docs + blank methods like this:
``` ruby
# app/docs/users_doc.rb
module UsersDoc
  include Apipie::DSL::Concern

  api :GET, '/users', 'List users'
  desc 'some description'
  def users
    # ... (nothing actually, just a blank method)
  end
end
```
And then include it into your controller anywhere (ancestors in this case are `[YourController, UsersDoc, ...]`, which means that you don't need to think about method overriding).

A little common solution: https://gist.github.com/IlyaBylich/c1e63767137528ab4d03

**Comment by jerry-tao** [comment]
@IlyaBylich Thanks. Sorry for reply later. I will close the issue.

**Comment by RajRoR** [comment]
Just a change in [@ghost's solution](https://github.com/Apipie/apipie-rails/issues/336#issuecomment-83031606). Updating for Rails 4.1 with Apipie-rails 0.5.6:

It needs to `extend Apipie::DSL::Concern` instead of `include Apipie::DSL::Concern`.

**Comment by Haniyya** [comment]
Seems like a duplicate of #584
