### ISSUE TITLE
APIPIE_RECORD=params tries updating description on api version 1 instead of 2 which is the default

### ISSUE THREAD

**Issue by zassmin** [Apipie/apipie-rails#337]
Trace: 
![screen shot 2015-02-23 at 5 19 39 pm](https://cloud.githubusercontent.com/assets/1654151/6341551/63939eb6-bb80-11e4-932e-50cbcaea4b52.png)

My apipie config is set to `config.default_version = '2.0'` 
When I open source and replace https://github.com/Apipie/apipie-rails/blob/master/lib/apipie/extractor.rb#L157 with `method_key = "#{Apipie.get_resource_name("Api::V2")}##{action}"` no error is thrown,  and get `Updating auto-generated documentation` but I don't actually see where the documentation is generated. 

What am I missing?

**Comment by alan-andrade** [comment]
Should we close this Issue ?
