### ISSUE TITLE
Headers documentation

### ISSUE THREAD

**Issue by IlyaBylich** [Apipie/apipie-rails#340]
Is it possible to document request headers? And if not, are you are going to implement in future releases (probably in the next one)? Thanks for a great documentation tool, btw.

**Comment by mtparet** [comment]
I don't think this is possible for now, I would like to do it too. (In particular for `if-match` header)

**Comment by IlyaBylich** [comment]
Basically it's not a problem to implement a DSL for defining request headers like
``` ruby
api :GET, "/users/:id", "Show user profile"
header 'Authentication', String, 'Auth header in format ...'
```
Is it possible to implement request headers recording during running specs? Any ideas?

**Comment by mtparet** [comment]
I think it should be possible, you could look around https://github.com/Apipie/apipie-rails/blob/master/lib/apipie/extractor/recorder.rb#L36

**Comment by IlyaBylich** [comment]
Well, it looks like the gem can fetch request headers. But how can I filter regular request headers (I mean, standard browser headers) from my API-specific headers?
For example, I have required 'Auth' header in my API. I suppose `test_context.request.headers` returns all passed headers (like `Accept`, `User-Agent`). The gem should detect that only `Auth` header is required for this particular request. And as I know, Rack automatically converts header's name from to `HTTP_AUTH`. Any ideas how to accomplish that? Probably some hard-coded list of default Rails headers?
