### ISSUE TITLE
Controller concerns

### ISSUE THREAD

**Issue by chrise86** [Apipie/apipie-rails#347]
I have a controller concern as follows:

```
module Pagination
  extend ActiveSupport::Concern

  included do
    before_action :set_limit_and_offset
  end

  def set_limit_and_offset
    # code here
  end
end
```

But when I load up the documentation url I get:

```
Unable to autoload constant Concerns::Pagination, expected /Users/<truncated>/app/controllers/concerns/pagination.rb to define it
```

**Comment by gkuhn1** [comment]
I did this workaround for this issue:

in the end of file *config/initializers/apipie.rb*

```ruby
class Apipie::Application
  alias_method :orig_load_controller_from_file, :load_controller_from_file
  def load_controller_from_file(controller_file)
    begin
      orig_load_controller_from_file(controller_file)
    rescue LoadError => e
       controller_file.gsub(/\A.*\/app\/controllers\//,"").gsub(/\.\w*\Z/,"").gsub("concerns/","").camelize.constantize
    end
  end
end
```

**Comment by IlyaBylich** [comment]
@chrise86 What is your rails version? Can you paste here an output of
```ruby
Rails.application.paths.keys
```
and
```ruby
Rails.application.paths['app/controllers/concerns']
```
There was a commit in rails which adds directory `app/*/concerns` to autoload paths. This means that with rails > 4.2 you can call your concern `Concernable` and place it to `app/controllers/concernable.rb` or to `app/models/concernable.rb`. But if you are using old version of rails (< 4.2) then you probably should change the name of your constant to `Concerns::Pagination` (and leave the code in `app/controllers/concerns/pagination.rb`)

@gkuhn1 Patching is not a good idea, for this problem there should be some simple solution

**Comment by gkuhn1** [comment]
@IlyaBylich
That is just a workaround if you need to use concerns with ApiPie ConcernsDSL

If you don't need to use ConcernsDSL, just change the (in *config/initializers/apipie.rb*)
```
config.api_controllers_matcher = "#{Rails.root}/app/controllers/**/*.rb"
```
to something that will not load concerns.

In this project, I'm using Rails 4.2 (Ruby 2.2.1) and defined concerns as
```ruby
module Index

  def self.included(base)
    base.send :include, BaseConcernController
  end

  def index
    if get_collection
      instance_variable_set('@q', get_collection.search(params[:q]))
      instance_variable_set(self.get_variable_plural, custom_order(instance_variable_get("@q").result).paginate(:page => params[:page]))
    end
  end

end
```
and put in *app/controllers/concerns/index.rb* (for organization). All other concerns stays in concerns folder too. We didn't liked to put them together with controllers.

**Comment by erlandsona** [comment]
@iliabylich I have a similar issue when I hit my /docs endpoint after generating the documentation with my specs...

I get `Unable to autoload constant Concerns::Authenticatable, expected ~/code/project/app/controllers/concerns/authenticatable.rb to define it`

Does ApiPie do autoloading different than Rails?

In `app/controllers/api_controller.rb` I have `include Authenticatable` which works fine until I try to hit /docs. I realize I could namespace the module under a coresponding Concern module it just seems a bit redundant? Unless I'm not properly understanding Rails Autoloading, which is possible...

**Comment by scashin133** [comment]
if you set api_controllers_matcher to something like

```ruby
config.api_controllers_matcher = "#{Rails.root}/app/controllers/{[!concerns/]**/*,*}.rb"
```

you will no longer have issues with autoloading.

**Comment by fernandodev** [comment]
@scashin133 Nice! It worked for me

**Comment by danielkummer** [comment]
Saldy @scashin133 solution didn't work for me. If I use the controller matcher like described, I'm getting the "Oops" message - when removing the concern everything is fine.

**Comment by damuz91** [comment]
I confirm in rails 3.2.13, ruby 1.9.3 and apipie 0.3.6 @scashin133 works

**Comment by LordLambda** [comment]
Running into the same problem as @danielkummer did. 

Using the api_controller_matcher provided:
`config.api_controllers_matcher = "#{Rails.root}/app/controllers/{[!concerns/]**/*,*}.rb"` 

```
Results in The same "Oops!! Resource <code></code> not found.
```

Ruby 2.2.3
Rails 4.14.2
Apipie 0.3.6

**Comment by danielkummer** [comment]
An update on this, @LordLambda - the best and easiest solution I've found is namespacing the api controllers under /controllers/api and adjusting the config.api_controllers_matcher path to this directory. 
This way, your concerns can stay **outside** the /api directory and apipie works as expected.

**Comment by beydogan** [comment]
@danielkummer's solution worked for me.

**Comment by chaomao** [comment]
```ruby
config.api_controllers_matcher = "#{Rails.root}/app/controllers/{[!concerns/]**/*,*}.rb"
```

I found previous solution didn't work for me
So I just write code to exclude any files in concers folder

```
config.api_controllers_matcher = Dir["#{Rails.root}/app/controllers/*"].map do |f|
    if f.include?('concerns')
      nil
    elsif f.include?('.rb')
      f
    else
      "#{f}/*.rb"
    end
  end.compact
```

**Comment by IlyaUmanets** [comment]
I resolved this problem differently. My controllers are in a `api` namesapce, so
`config.api_controllers_matcher = "#{Rails.root}/app/controllers/api/*.rb"`

**Comment by robikovacs** [comment]
This worked for me: 
`config.api_controllers_matcher = Rails.root.join('app', 'controllers', 'api', '**', '*.rb')`

**Comment by speckins** [comment]
```ruby
# Relevant excerpts from lib/apipie/application.rb
module Apipie
  class Application
    # ...
    def api_controllers_paths
      Dir.glob(Apipie.configuration.api_controllers_matcher)
    end

    def reload_documentation
      # ...
      api_controllers_paths.each do |f|
        load_controller_from_file f
      end
      # ...
    end

    def load_controller_from_file(controller_file)
      controller_class_name = controller_file.gsub(/\A.*\/app\/controllers\//,"").gsub(/\.\w*\Z/,"").camelize
      controller_class_name.constantize
    end
  end
end
```

I think that `#load_controller_from_file` shouldn't be assuming that the file contains a constant of the same name.  While it is a strongly held convention, especially in Rails, that constants map to file names, IMHO an API documentation gem shouldn't be making an application crash because of this.
* Why not use [#safe_constantize](https://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-safe_constantize) instead of #constantize to avoid NameErrors when the file doesn't contain the expected constant?
* I'm not sure #constantize should be used in the first place.  As far as I know, it invokes Rails constant lookup, which may look in load paths other than the one(s) configured by api_controllers_matcher.
* Apipie is inferring a hypothetical constant name based on an actual file name in order to get Rails to load the constant(s) in the actual file.  What it really wants to do is to load the file and any constants defined in it.  There is an ActiveSupport method, [#require_dependency](https://api.rubyonrails.org/classes/ActiveSupport/Dependencies/Loadable.html#method-i-require_dependency), that loads files in a way that is compatible with Rails constant reloading.
* A concerns/ directory has been part of the default Rails file layout [since version 4.0.0](https://github.com/rails/rails/commit/f6bbc3f582bfc16da3acc152c702b04102fcab81).  Apipie should be taking this into consideration.
