### ISSUE TITLE
Apipie with Devise authentication

### ISSUE THREAD

**Issue by yoyos** [Apipie/apipie-rails#349]
I just made a cool API and documented it with Apipie. The problem is my doc page is public and I would like it to use my authentication system already in place.

I'm using Devise and I don't really now how to do it.

Here is what I found about apipie authentication on github page:

Create a /config/initializers/apipie.rb with:

```
Apipie.configure do |config|
  config.authenticate = Proc.new do
     authenticate_or_request_with_http_basic do |username, password|
       username == "test" && password == "supersecretpassword"
    end
  end
end
```
I would like to avoid basic auth. How could I extend the ApipiesController to use my Devise authentication ?

Thanks !

**Comment by saneshark** [comment]
@iNecas this really ought to be documented in the README, took me a little while to figure it out. Let me know if you would like me to add a PR to the README.

@yoyos 

```ruby
    config.authenticate = Proc.new do
      authenticate_admin_user!
    end
```

worked for me, where `:admin_user` is scope that I've created in `config/initializers/devise.rb` Devise will automatically create the helper method above and it can be used in the context of your routes which Apipie simply extends.

An alternate approach would be to do something like the following:

```ruby
  scope 'apis/documentation' do
    authenticate :admin_user, lambda {|u| u.admin_user? } do
       apipie
    end
  end
```

Or something to that effect, but then you really have to play with `config.api_base_url` and `config.doc_base_url` as those don't properly anticipate having a scope -- it will doesn't play very nice with apipie being in a scope (though I think it should for the sake of being consistent with how other gems do this type of thing).

**Comment by yoyos** [comment]
@saneshark Thanks ! Very helpful :)
