### ISSUE TITLE
undefined method `content_tag' for Apipie::ApipiesController

### ISSUE THREAD

**Issue by yoyos** [Apipie/apipie-rails#353]
Showing C:/Ruby21/lib/ruby/gems/2.1.0/gems/apipie-rails-0.3.4/app/views/apipie/apipies/_method_detail.erb where

 line 9 AND 34 

raised:

undefined method `content_tag' for #<Apipie::ApipiesController:0xd10b3b0>
Trace of template inclusion: C:/Ruby21/lib/ruby/gems/2.1.0/gems/apipie-rails-0.3.4/app/views/apipie/apipies/method.html.erb

This error occurs only with last 0.3.4 gem version. 0.3.3 was OK.

My code sample:

``` 
    api :POST, '/test.json', 'Test title'
    param :phone, String, required: true, desc: 'Phone'
    error 500, 'Error occurred'
    description <<-EOS
      All parameters are case insensitive.
      This webservice let you request a test      
      == JSON Status 200
    EOS
    def request_test
       (...)
    end
```

**Comment by zeitnot** [comment]
I have the same problem. I am using `'rails', '4.1.9'`.

**Comment by yoyos** [comment]
I'm using gem 'rails', '4.2.1'

**Comment by yoyos** [comment]
I tested to include ActionView::Helpers::TagHelper and it seems to work.

**Comment by zeitnot** [comment]
@yoyos Where did you add this?

**Comment by yoyos** [comment]
in the helper or controller. Don't know the right place but it worked in both.

**Comment by thiensubs** [comment]
I think Helper file is good then controller.
https://github.com/Apipie/apipie-rails/blob/master/app/helpers/apipie_helper.rb
And i was added:
include ActionView::Helpers::TagHelper
include ActionView::Context
And file helper will be:

module ApipieHelper
  include ActionView::Helpers::TagHelper
  include ActionView::Context
  def heading(title, level=1)
    content_tag("h#{level}") do
      title
    end
  end
end

**Comment by bastengao** [comment]
I heavily expect this fix to be released in new version.

**Comment by avokhmin** [comment]
> I heavily expect this fix to be released in new version.

+1

**Comment by FlySnake** [comment]
+1

**Comment by dbackowski** [comment]
:+1:

**Comment by lasloandrei** [comment]
it affected rails 4.2.2 as well, the fix works

**Comment by GabKlein** [comment]
+1
