### ISSUE TITLE
Method not found for resource

### ISSUE THREAD

**Issue by ericpeters0n** [Apipie/apipie-rails#359]
Numerous comments suggest https://github.com/Apipie/apipie-rails/issues/171 should be reopened (or a new issue should be clarified)... Use of documented configuration doesn't appear to be reliably working for people outside of the demo app.

**Comment by legkvla** [comment]
May be it could be useful for somebody. I've got this error away when comment in version in resourse description:
```
resource_description do
      short 'API authentication'
      formats ['json', 'xml']
      #api_version "v1"
end
```

**Comment by Pajk** [comment]
Let's solve this in the issue #171.
