### ISSUE TITLE
Option to allow custom required params error messages

### ISSUE THREAD

**Issue by holyxiaoxin** [Apipie/apipie-rails#360]
Right now params error messages are based on the params names. Sometimes, param names does not reflect the input labels from client. Any alternative solutions would be great. (:

**Comment by Pajk** [comment]
@holyxiaoxin thanks to @jcalvert it's now possible to set your custom message for missing parameters. Use `gem 'apipie-rails', :github => 'apipie/apipie-rails', :branch => 'master'` in your `Gemfile` or wait until next version is released.
