### ISSUE TITLE
remove /api in front of requests

### ISSUE THREAD

**Issue by WorkForPizza** [Apipie/apipie-rails#367]
In the generated docs, all of our endpoints are being prefixed with a /api. For example, it will say `GET /api/v3/users` when we want it to say `GET /v3/users`. There doesn't seem to be an option to remove this prefix.

**Comment by isseu** [comment]
I think you refer to this option in the file `initializers/apipierb`
```ruby
Apipie.configure do |config|
...
  config.api_base_url            = "/api" # <-- change this
...
end
```

**Comment by WorkForPizza** [comment]
Unfortunately, no. I'm not sure what that changes but it does not fix the problem.

**Comment by Pajk** [comment]
@WorkForPizza It seems that what you want to do is:

    config.api_base_url["v3"] = "/"

see https://github.com/Apipie/apipie-rails/issues/383 for more info
