### ISSUE TITLE
Tests don't run with Apipie

### ISSUE THREAD

**Issue by tdeo** [Apipie/apipie-rails#391]
Hi,

I've manage to set up apipie on a Rails app having ~300 API endpoints on several controllers.

At first, I added the `api!` keyword to the methods of only one controller, and I was able to generate the examples from the tests and then the static documentation without problem.

Now that I have added `api!` to all the endpoints, I ran `rake apipie:statis` to generate the doc, which worked, but took ~10 minutes. Also, I can't run any tests on my controllers, rspec starts correctly, but the actual tests are never run. Also, running tests on a model still work perfectly.

Anyone has an idea of what's going on? Is that a known issue?

Thanks

UPDATE: actually, the tests run, but apipie takes ~8 minutes generating data because of the api! statements. Any idea how I could speed it up ?

**Comment by joshpfosi** [comment]
Using the caching feature helped me significantly!

**Comment by Pajk** [comment]
@tdeo So the only issue here is speed? Did you manage to solve it somehow? Let us know otherwise I will close this issue in few days.

**Comment by tdeo** [comment]
I guess I hadn't made a good setup at the time, and it works properly now.
