### ISSUE TITLE
param :description causes error

### ISSUE THREAD

**Issue by casiodk** [Apipie/apipie-rails#398]
def_param_group :assessment do
    param :assessment, Hash, desc: 'Assessment info' do
      param :name, String, desc: "", required: true
      param :description, desc: "", required: false
    end
  end

**Comment by Pajk** [comment]
What issues exactly? You have to specify param type for `description` to make your code work:  

    def_param_group :assessment do
      param :assessment, Hash, desc: 'Assessment info' do
        param :name, String, desc: "", required: true
        param :description, String, desc: "", required: false
      end
    end
