### ISSUE TITLE
Bump gem to 0.3.5

### ISSUE THREAD

**Issue by Velocity-** [Apipie/apipie-rails#399]
Since 0.3.4 a few critical fixes were made which fixed issues that we ran into. However, the gem hasn't been bumped 0.3.5, and using the github repository on a production server fails to run.

Could this gem please be bumped to 0.3.5 as soon as possible? 0.3.4 seems somewhat ancient looking at what changed since.

Thanks.

**Comment by mjansing** [comment]
+1

**Comment by johan-smits** [comment]
+1

**Comment by wired9** [comment]
+1

**Comment by alex-zige** [comment]
good idea!

**Comment by iNecas** [comment]
0.3.5 released, Thanks for the patience :) Cheers

**Comment by Velocity-** [comment]
Thank you @iNecas, much appreciated!
