### ISSUE TITLE
Multiple api for one function do not show param_group settings

### ISSUE THREAD

**Issue by johan-smits** [Apipie/apipie-rails#401]
I have in the companies controller this section:
<code>
```ruby
  resource_description do
    short 'Companies'
    formats ['json']
  end

  def_param_group :companies do
    param :id, Integer, :required => true
    param :name, String, :required => true
    param :created_at, String
    param :updated_at, String
  end

 api :GET, 'companies', 'Retrieve all company resources' do
    param_group :companies
  end

  def index
    #....
  end
```
</code>

But the ouput opening the apipie does not show the param_group.

I have found an old thread about it on google: https://groups.google.com/forum/#!topic/foreman-dev/qHs5Cw4DwsU

But it does not mention if it was implemented.

Using version 0.3.5

**Comment by halilim** [comment]
You should put `param_group` outside the block:

```ruby
api :GET, 'companies', 'Retrieve all company resources'
param_group :companies
```

**Comment by Pajk** [comment]
@johan-smits As this is quite old question and @halilim suggestion should work I'm closing this. Let us know if not.
