### ISSUE TITLE
Empty string not recognized by allow_nil

### ISSUE THREAD

**Issue by joshpfosi** [Apipie/apipie-rails#402]
A usage issue: Due to the current implementation of `validate`, a parameter with `allow_nil` set will still be rejected if that parameter is the empty string as `"".nil? #=> false`. I propose changing the conditional check in `validate` to:

```ruby
      return true if @allow_nil && value.to_s.blank?
```

This way both `nil` and `""` are acceptable. I intend to make a fork with this change and will generate a PR. I was wondering, however, if this is perhaps a feature not a bug?

Thanks!

**Comment by Pajk** [comment]
Please see https://github.com/Apipie/apipie-rails/pull/403#issuecomment-164144590
