### ISSUE TITLE
api! not working with Rails 5.0.0.beta1

### ISSUE THREAD

**Issue by gniding** [Apipie/apipie-rails#415]
"api!" seems not to work with Rails 5.0.0.beta1 as methods using api! do not appear at all in the index page. Other than that it works fine so far.

It appears to do with routes_for_action method in application.rb (https://github.com/Apipie/apipie-rails/blob/master/lib/apipie/application.rb) from line 67

```
def routes_for_action(controller, method, args) 
       routes = rails_routes.select do |route| 
         controller == route_app_controller(route.app, route) && 
             method.to_s == route.defaults[:action] 
       end 

       Apipie.configuration.routes_formatter.format_routes(routes, args) 
end 
```

Not sure what is wrong with the route_app_controller method call in the inner expression of the select as it yields false when it should yield true.

However I managed to crudely modify it a bit (adding a controller name comparison) as a makeshift workaround:

```
 def routes_for_action(controller, method, args)
      routes = rails_routes.select do |route|
        (controller == route_app_controller(route.app, route) || 
            controller.to_s.chomp("Controller").downcase.sub("::", "/") == route.defaults[:controller]) &&
            method.to_s == route.defaults[:action]
      end

      Apipie.configuration.routes_formatter.format_routes(routes, args)
    end
```

**Comment by neilgupta** [comment]
I am seeing this on Rails 4.2.5.1 as well.

**Comment by sblackstone** [comment]
This bug is a regression of

https://github.com/rails/rails/commit/4276b214f8a13a38ac7dc4911e90d295a8e40d5a#diff-ccdef70ce0e95afc8816f47f89b56c60

**Comment by sblackstone** [comment]
PR #465 Fixes this

**Comment by aminariana** [comment]
+1

**Comment by aminariana** [comment]
Please note that `Apipie` is completely useless in `Rails 5` right now.

I'm surprised so few people ran into this issue for the last year. Am I missing anything or running into a corner case?

**Comment by casiodk** [comment]
Any progress here?

**Comment by Neonrat** [comment]
+1 for this. Can it be bumped, priority wise?

**Comment by rebekah** [comment]
I also vote that this item be raised in priority if possible.

**Comment by iNecas** [comment]
Closed by https://github.com/Apipie/apipie-rails/pull/527

**Comment by iNecas** [comment]
apipie-rails-0.4.0 has just been released, the issues should be resolved there
