### ISSUE TITLE
`request_data` is producing a string instead of a hash

### ISSUE THREAD

**Issue by alienxp03** [Apipie/apipie-rails#417]
I'm recording an Example as shown below:

```ruby
params = {
  email: 'username',
  password: 'password'
}

it 'should retrieve user', :show_in_doc do
  post '/api/sessions', params
end
```

I'm expecting to `request_data` to be something like
```ruby
"request_data": {
  "email": "MyPassword",
  "password": "MyString"
}
```

But I'm getting this instead:
```ruby
"request_data": "email=MyPassword&password=MyString",
```

In general, it works. But the `request_data` produced different that I'm expected.

**Comment by Pajk** [comment]
@alienxp03 Did you find the solution? Could you share it here just in case someone has the same problem?

**Comment by alienxp03** [comment]
It's related to this question that I asked on Stackoverflow

http://stackoverflow.com/questions/34709206/rspec-controller-not-behaving-as-expected/34723581#34723581

So basically, I'm writing a `controller` rspec, something like `describe Api::SessionsController, :type => :controller`. But since I put it in `spec/api` folder, and not in the `spec/controllers` folder, it's detecting my tests as `request` spec. I just need to move it to `spec/controllers/api`, and it will detect it as a controller test and everything works fine.

I have a question though. Does it mean that the `request_data` will produce a string parameters instead of a hash if the RSpec being recorded is a `request` rspec, and not a `controller` rspec?

**Comment by Pajk** [comment]
I don't think so. It looks that what you did in your example is not sending a json in the body. Instead it uses the hash to construct query string.

See http://stackoverflow.com/questions/2103977/how-to-send-raw-post-data-in-a-rails-functional-test
