### ISSUE TITLE
Broken after updating rails from 4.2.5 to 4.2.5.1

### ISSUE THREAD

**Issue by mmozuras** [Apipie/apipie-rails#421]
After updating rails from `4.2.5` to `4.2.5.1`, `apipie:cache` rake task started failing.

This change seems to be the cause:
https://github.com/rails/rails/commit/0c5c32aa7cea5ee1ea60bd1f87dfa5c7e7146a54

Release notes:
http://weblog.rubyonrails.org/2016/1/25/Rails-5-0-0-beta1-1-4-2-5-1-4-1-14-1-3-2-22-1-and-rails-html-sanitizer-1-0-3-have-been-released/

Error:
```
ActionView::MissingTemplate: Missing template ../../layouts/apipie/apipie with {:locale=>[:"en-dev"], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee]}. Searched in:
actionview-4.2.5.1/lib/action_view/path_set.rb:46:in `find'
actionview-4.2.5.1/lib/action_view/lookup_context.rb:121:in `find'
actionview-4.2.5.1/lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:86:in `resolve_layout'
actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:76:in `block in find_layout'
actionview-4.2.5.1/lib/action_view/lookup_context.rb:252:in `with_layout_format'
```

**Comment by TimThaler** [comment]
I am having the exact same problem. Also after updating from Rails 4.25 to 4.2.5.1

**Comment by FooBarWidget** [comment]
Me too.

**Comment by FooBarWidget** [comment]
I've fixed this locally as follows. Edit apipie-rails-0.3.5/lib/tasks/apipie.rake. Look for:

    @apipie_renderer = ActionView::Base.new(base_path)

Replace with:

    layouts_path = File.expand_path("../../../app/views/layouts", __FILE__)
    @apipie_renderer = ActionView::Base.new([base_path, layouts_path])

Look for:

    f.write av.render(
      :template => "#{template}",
      :layout => (layout && "../../layouts/apipie/#{layout}"))

Replace with:

    f.write av.render(
      :template => "#{template}",
      :layout => (layout && "apipie/#{layout}"))

**Comment by buiatte** [comment]
Same problem on rails 4.2.5.1, works fine on 4.2.5

**Comment by buren** [comment]
I'm also seeing this under 4.2.5.1...  (and Rails 5.0.0.beta2)

**Comment by laurynas** [comment]
:+1:
