### ISSUE TITLE
Can't modify frozen string literal exception

### ISSUE THREAD

**Issue by samphilipd** [Apipie/apipie-rails#461]
Apiepie appears to destructively modify configuration strings. This is incompatible with the following example file in Ruby >= 2.3:

``` ruby
# frozen_string_literal: true
Apipie.configure do |config|
  config.default_version = '1.0'
end
```

**Comment by mathieugagne** [comment]
This is still an issue. When using `rubocop` it'll add the `frozen_string_literal` comment to the top of all files if the right cop is active.
