### ISSUE TITLE
allow `error` to support Rails status symbols

### ISSUE THREAD

**Issue by alex-tan** [Apipie/apipie-rails#466]
Would you be open to the idea of accepting a PR that allows you to specify a Rails status code symbol (:ok, :not_found, etc..) but continue outputting the actual status to the docs?

Example:

``` ruby
error 404, 'Missing'
# becomes
error :not_found, 'Missing'
```

A full list can be found [here](http://guides.rubyonrails.org/layouts_and_rendering.html) in section 2.2.13.

**Comment by iNecas** [comment]
Hi, I think it's reasonable.

**Comment by iNecas** [comment]
apipie-rails 0.5.1 released, including fix for this issue
