### ISSUE TITLE
api! still not working with Rails 5.0.0.1

### ISSUE THREAD

**Issue by aminariana** [Apipie/apipie-rails#510]
Repro:
- Use Rails 5.0.0.1
- Use Apipie 0.3.7
- Call `api!`.

Expected:
Documents render as usual.

Actual:
API Documentation has become useless. Nothing action-related renders. See screenshot. (Not using api! and instead using the long-hand fixes the issue, but highly undesirable.)

Note:
Issue #415 deals with Rails 5.0.0.beta, but has not been resolved in 6 months. I wanted to explicitly mention that the bug persists, even in the non-beta Rails.

Screenshot:
![blank](https://cloud.githubusercontent.com/assets/1071917/21326063/f54f3e28-c5dd-11e6-9a1d-d106c8a31b56.png)

**Comment by iNecas** [comment]
Closed by https://github.com/Apipie/apipie-rails/pull/527

**Comment by iNecas** [comment]
apipie-rails-0.4.0 has just been released, the issues should be resolved there
