### ISSUE TITLE
Rdoc is always required

### ISSUE THREAD

**Issue by xHire** [Apipie/apipie-rails#544]
I’m trying to setup an application to use maruku as apipie markup and I don’t have rdoc gem installed. However, I constantly run into:

    /home/xhire/.gem/ruby/2.2.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- rdoc (LoadError)
    	from /home/xhire/.gem/ruby/2.2.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `block in require'
    	from /home/xhire/.gem/ruby/2.2.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
    	from /home/xhire/.gem/ruby/2.2.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
    	from /home/xhire/.gem/ruby/2.2.0/gems/apipie-rails-0.5.1/lib/apipie/markup.rb:8:in `initialize'
    	from /home/xhire/.gem/ruby/2.2.0/gems/apipie-rails-0.5.1/lib/apipie/configuration.rb:139:in `new'
    	from /home/xhire/.gem/ruby/2.2.0/gems/apipie-rails-0.5.1/lib/apipie/configuration.rb:139:in `initialize'
    	from /home/xhire/.gem/ruby/2.2.0/gems/apipie-rails-0.5.1/lib/apipie/apipie_module.rb:26:in `new'
    	from /home/xhire/.gem/ruby/2.2.0/gems/apipie-rails-0.5.1/lib/apipie/apipie_module.rb:26:in `configuration'
    	from /home/xhire/.gem/ruby/2.2.0/gems/apipie-rails-0.5.1/lib/apipie/apipie_module.rb:22:in `configure'
    	from /home/xhire/devel/web/apipie-test/config/initializers/apipie.rb:1:in `<top (required)>'

The initializer is irrelevant since I can comment it out and the exception would come from `config/routes.rb` instead. But for the sake of completeness:

```ruby
Apipie.configure do |config|
  config.markup = Apipie::Markup::Markdown.new
end
```

If I comment out the line `apipie-rails-0.5.1/lib/apipie/configuration.rb:139`, everything is fine again. From what I can see, the code first sets default values and then lets the block change them. Either this should be reversed or the set markup should be instantiated later when everything is already set up or the class `Configuration` could have a reader method for `@markup` that would handle the default (or something else :c)).

**Comment by vkrizan** [comment]
I guess this can be also resolved by changing the documentation.
