### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by HienNguyenAsnet** [Apipie/apipie-rails#549]
I have language issue when use v0.5.1. I don't config any language for document but when click link on document. I got error
```
Oops!! Method index.en not found for resource events.
```

**Comment by yakjuly** [comment]
same when I use v0.5.2, currently, I configure as below to avoid link issue.

```
config/initializers/apipie.rb
Apipie.configure do |config|
  config.translate         = false
  config.default_locale = nil
  ...
end
```

**Comment by markmoser** [comment]
If I set default_locale to nil in my config file while using `apipie-rails (0.5.4)` the live site works great. However, `rake apipie:static` throws an error:
> Writing examples to a file
> rake aborted!
> I18n::InvalidLocale: nil is not a valid locale

**Comment by iNecas** [comment]
Closing via https://github.com/Apipie/apipie-rails/pull/562

**Comment by OrrYakobi** [comment]
> same when I use v0.5.2, currently, I configure as below to avoid link issue.
> 
> ```
> config/initializers/apipie.rb
> Apipie.configure do |config|
>   config.translate         = false
>   config.default_locale = nil
>   ...
> end
> ```

This should be added to the documentation!
