### ISSUE TITLE
api! break apipie

### ISSUE THREAD

**Issue by phspies** [Apipie/apipie-rails#551]
When using api :method, "<route>" in a controller all works fine. The moment I try to use api!, the following error is seen "uninitialized constant OculusController"

**Comment by Haniyya** [comment]
@phspies Had the same problem. My problem was that i had 'dangeling routes' in `conf/routes.rb`. 
Something like `resources :oculus` or something might create routes to controllers that don't exist (anymore).

So the solution is to either delete those routes in `routes.rb` or not to use `api!`.

**Comment by Haniyya** [comment]
That said, it would probably be a good idea to catch those errors somewhere since this is not really an informative or expected error.

**Comment by Haniyya** [comment]
I guess this could be closed now.

**Comment by iNecas** [comment]
yes, thanks for heads up
