### ISSUE TITLE
apipie makes my controllers big

### ISSUE THREAD

**Issue by AmrAdelKhalil** [Apipie/apipie-rails#573]
I got a rails api application and i searched a lot about a gem that i can use to make a well defined documentation for my APIs, I found apipie and it seems to be very good gem but after a while of using it i noticed that some controllers became very big, I found myself writing about 100+ line to just make a documentation to a create function(it receives a lot of params), the problems was in `description` part in which i i'm showing the user the structure of the JSON request, So i'm asking this why wouldn't `apipie` separate documentation code from controllers, Something like `Pundit` policy gem structure if you aware about it(it put policies in an external file in which every function maps a function in the controller followed by '?'), If there is a best practice for using `apipie` please tell me the right way to do so.

Thanks

**Comment by Haniyya** [comment]
@AmrAdelKhalil 
1. Your controllers might have more lines, but not more logic. The 'thin controllers, fat models' mantra that is (deservedly) best practice in rails refers to less logic, not strictly less lines. So while it might be harder to read the source code, there should not be a direct impact on code quality (not a negative one at least). 
2. If your examples are to big, you might want to take a look at the `Recording examples` section in the README. You can keep your documentation thinner by relying on your tests to provide documentation.

**Comment by AmrAdelKhalil** [comment]
@Haniyya 

Sorry my late response, I truly appreciate yours for your second point I didn't read this before, It's my mistake and I totally agree with the integration of documentation with test cases.

For the first point I want to discuss something with you, you said `here should not be a direct impact on code quality`, Projects are not perfect, I should have to say "Nobody's perfect" but in our case let it Projects :D, I believe that you shouldn't depend on hoping that people will follow some mantra or principle, I believe that you should put your all consideration for all types of projects, but at last `api-pie` is an amazing gem, I totally agree with that, but separating doc code from the controller or even parameters description to a separated files will be better.

I will close this issue now.
Thank you very much

**Comment by Haniyya** [comment]
@AmrAdelKhalil 

I agree that people might see the apipie code in the controller and won't dry it up as thoroughly since there are already so many lines (even though they are outside of the actions). 
I was just talking about moving apipie-documentation to an external file with my colleague and your issue might just be the best argument about moving the docs to external files (although I don't have a complete plan how to do this as of right now). 

If you don't mind I would like to open a new issue for discussing the possibility of external documentation.

**Comment by AmrAdelKhalil** [comment]
@Haniyya 

Of course i don't mind opening a new issue, Wish you all luck with finding a new plan.
