### ISSUE TITLE
Ruby Versioning Support 2.4

### ISSUE THREAD

**Issue by PrimeTimeTran** [Apipie/apipie-rails#587]
Hey guys, 
Does Apipie-rails support ruby 2.4? I see you guys are actively maintaining it, awesome! I read through the documentation and didn't see a mention of supported Ruby versions so I opened this PR.

Cheers!

**Comment by iNecas** [comment]
Not aware of anything breaking there, but enabled travis for this version here https://github.com/Apipie/apipie-rails/pull/590, let's see
