### ISSUE TITLE
Failed to install on windows because of symlink

### ISSUE THREAD

**Issue by wrystr** [Apipie/apipie-rails#594]
AFAIK Windows doesn't support File.symlink, soinstallation on windows will fail. I tried Ruby 2.3 with DevKit and Ruby 2.4 with MSYS2 and I tried all of 0.5.x versions, version 0.4.0 works.

Is there any plan to support latest version of the gem on Windows?

Thank you for developing this gem, it is awesome.

**Comment by iNecas** [comment]
I don't expect to get to this issue, but I'm willing to review (not test though, as I don't have windows at my hands) if someone will open a PR that will fix it.

**Comment by yasz** [comment]
could you please preview this issue?

**Comment by jirubio** [comment]
@mathieujobin this is fixed since 0.7.1, same issue #704

**Comment by mathieujobin** [comment]
ah thanks, I usually disregard anything Microsoft Windows.
