### ISSUE TITLE
$PARAMETER is optional but default value is not specified

### ISSUE THREAD

**Issue by dlo** [Apipie/apipie-rails#596]
Here's an example warning I receive when generating Swagger documentation using apipie.

```
WARNING (105): [Api::V1::UsersController#create] -- the parameter :image_url is optional but default value is not specified (use :default_value => ...)
```

It feels like this error is backwards. Shouldn't only required parameters require a default?

**Comment by iNecas** [comment]
I don't think so: think about it as required vs optional args in ruby: the optional ones are those that hav the default value specified, so that the user doesn't have to specify them
