### ISSUE TITLE
Apipie versions upper 0.5.6 doesn't generate docs for rails 4.2

### ISSUE THREAD

**Issue by korrs** [Apipie/apipie-rails#622]
And i [found](https://github.com/Apipie/apipie-rails/commit/e3eab0a33eaff8e8311eee3f478feabde7d906ae) commit that brakes the generation of docs. When i remove changes in this commit all works excellent and all specs in gem completed without errors(with various rails versions).

**Comment by korrs** [comment]
👌

**Comment by korrs** [comment]
@iNecas can i revert changes in mentioned commit?

**Comment by iNecas** [comment]
I would rather see a condition on Rails version, and use the old variant for rails < 5. I bet there was a reason for doing the original patch in some environments (don't remember the details though)

**Comment by morr** [comment]
@iNecas currently docs generation is broken in rails 5.2 in latest apipie version
When i reverted changes from https://github.com/Apipie/apipie-rails/commit/e3eab0a33eaff8e8311eee3f478feabde7d906ae docs generation starts working again.
