### ISSUE TITLE
Stop swagger generation from crashing (if a controller's parent doesn't define a resource_description block)

### ISSUE THREAD

**Issue by enrique-guillen** [Apipie/apipie-rails#638]
This is a post-PR issue I made for this bugfix: https://github.com/Apipie/apipie-rails/pull/637

>The original feature release made Apipie's swagger generator (rake apipie:static_swagger_json) to crash with this error:

```ruby
NoMethodError: undefined method `_tag_list_arg’ for nil:NilClass
```

> Unless you happened to define a resource_description for the parent class of a controller. (It turns out the parent variable isn't always a resource-desc object.)

>This makes sure _tag_list_arg is called on non-nil objects only. I marked this as a bugfix because the error message you get doesn't explain how to fix it, and we shouldn't have to define resource_description for the parent classes.

>0.5.11 should be marked as faulty. Sorry about that.

~I will make a quick local test with my project to verify the PR is good to merge.~

**Comment by enrique-guillen** [comment]
Nevermind that last point, I inspected the new specs I made and I think the code is good enough now (PR ready for merging, I have yet to understand why `@resource` is always not-null though). I will still comment here (tomorrow) if the test with my project works.

**Comment by enrique-guillen** [comment]
My PR branch fixed my project's swagger generation.

**Comment by enrique-guillen** [comment]
Sorry for the insistence, but I would love to see a merge on this. My original method is now unnecessarily crashing the `apipie:static_swagger_json` command on the simpler setups all across the board, even if you don't define tags at all.

**Comment by alexisraca** [comment]
+1 to this. Swagger is a great addition to fix this issue.

**Comment by iNecas** [comment]
Hi, thanks for patience: maintaining apipie is not my full-time job, so please be patient :) Getting a release with the fix 2 days after a PR open is IMO still way above the standard response rate in most of the oss projects :) Thanks for the contribution.

**Comment by iNecas** [comment]
Closed as https://github.com/Apipie/apipie-rails/pull/637 got merged and released: for the future, no need to create an issue, if there is PR already opened.

**Comment by enrique-guillen** [comment]
Thanks a lot for merging, just got a bit too worried about breaking the `static_swagger_json` command for half the userbase (well... of the last 2 releases, anyways). It all looks fine now, however. :)
