### ISSUE TITLE
Self describing class attributes are not shown

### ISSUE THREAD

**Issue by amiracruceru** [Apipie/apipie-rails#643]
Hello, I try to make use of the 'Embedded response descriptions' but it is not showing the actual parameters, only this:

![returns](https://user-images.githubusercontent.com/42737103/48361632-31d60480-e6a2-11e8-9749-384232ee7b3f.png)

I tried the dummy project as well and I see the same problem:

![pets class](https://user-images.githubusercontent.com/42737103/48361598-284c9c80-e6a2-11e8-88dd-798bc5e6d276.png)

This is what I have in the controller:
 
```ruby
returns :array_of => Comment
```

And this is what I have in the `Comment` class:

```ruby 
def self.describe_own_properties
    [
        Apipie::prop(:id, Integer, {:description => 'The id of the comment', :required => false}),
        Apipie::prop(:content, String, {:description => 'The content of the comment', :required => false}),
    ]
end
```

Do you know what can be the problem? Thank you in advance!

**Comment by boza** [comment]
is there a solution for this?

**Comment by ccelestial** [comment]
I'm having the same problem

**Comment by mgpoole4** [comment]
Also experiencing this problem. Please help!
