### ISSUE TITLE
Setting swagger_content_type_input to :json does not change 'consumes' values

### ISSUE THREAD

**Issue by belgoros** [Apipie/apipie-rails#652]
As for README guidelines regarding [Swagger-Specific Configuration Parameters](https://github.com/Apipie/apipie-rails#swagger-specific-configuration-parameters), I set up `swagger_content_type_input` to `:json` in `apipie.rb` initiliazer as follows:
```
Apipie.configure do |config|
  config.app_name                = "Draft API"
  config.api_base_url            = "/"
  config.doc_base_url            = "/apidocs"
  config.swagger_content_type_input = :json
  # where is your API defined?
  config.api_controllers_matcher = "#{Rails.root}/app/controllers/**/*.rb"
end
```
After running `rake apipie:static_swagger_json` rake task, there are no changes in the generated `schema_swagger_form_data.json` file:
```
"consumes": [
    "application/x-www-form-urlencoded",
    "multipart/form-data"
  ],
```
instead of expected `application/json`.

**Comment by nullnull** [comment]
@belgoros 
`rake apipie:static_swagger_json` task does not use configured value.
You should specify `swagger_content_type_input` by argument (ex. `bundle exec rake apipie:static_swagger_json[1.0,json]` )

See [my PR](https://github.com/Apipie/apipie-rails/pull/648).

**Comment by iNecas** [comment]
Fixed by https://github.com/Apipie/apipie-rails/pull/648
