### ISSUE TITLE
[Feature Request] Support for Rails 6

### ISSUE THREAD

**Issue by kirantpatil** [Apipie/apipie-rails#662]
Hi,

Please add support for Rails 6 which is planned to release on April 2018.

Thanks.

**Comment by ce07c3** [comment]
2019* :)

**Comment by ce07c3** [comment]
And yeah, this would be great! How can I help?

**Comment by iNecas** [comment]
@ce07c3 a pull request would be the best :)

**Comment by ce07c3** [comment]
No shit :) I mean, more specifically, what has to be done? I'm new to gem development.

**Comment by iNecas** [comment]
1. create `Gemfile.rails6` with corresponding version references
2. update Gemfile to use this file
3. run `bundle exec rake spec`
4. make the tests green (I have not looked in detail what actually gets broken in rails 6, but the tests should be a good generater of a TODO list)

**Comment by ce07c3** [comment]
@iNecas thanks :) I'll try to do that over the weekend. Sorry for being a bit blunt, but it goes both ways - I want to help so I'll need guidance, just creating a PR won't make me understand where to start digging.

**Comment by iNecas** [comment]
Sure, it's just about finding the right level of abstraction we're talking in: we didn't have this at the beginning of this conversation, but we have it now I hope.

**Comment by SaimonL** [comment]
At the moment I am getting this error in Rails 6

`
NameError - uninitialized constant Concerns
Did you mean?  Concurrent:

Started POST "/__better_errors/bb80da3cbf28c410/variables"
`

**Comment by dirkjonker** [comment]
All the specs seem to pass with Rails 6, you do need the development version of Rspec though.
And there's about thousand deprecation warnings for `Fixnum` usage.
https://github.com/Apipie/apipie-rails/compare/master...dirkjonker:rails6?expand=1

**Comment by iNecas** [comment]
Thanks, I've opened a PR to add the rails 6 to the travis matrix https://github.com/Apipie/apipie-rails/pull/664, this might be a good start to nail this.

**Comment by iNecas** [comment]
@SaimonL could you give apipie-rails-0.5.16 a try, I suspect https://github.com/Apipie/apipie-rails/pull/665 might help your issue

**Comment by SaimonL** [comment]
Confirmed it works on "Rails 6.1.0.alpha"
