### ISSUE TITLE
Minimization rails dependency

### ISSUE THREAD

**Issue by mr-dxdy** [Apipie/apipie-rails#701]
Hi! I uses in my project only actionpack, activesupport, actionview, railties. 

May be change dependency `apipie-rails` from 
`s.add_dependency "rails", ">= 4.1"` 
to 
`s.add_development_dependency "rails", ">= 4.1"` 

I found pull-request [reduced rails dependency to development only](https://github.com/Apipie/apipie-rails/pull/266/files). Why was dependency rollback? I don't want install on my server actioncable, actionrecord and etc. I have a limit on free space on the server.

**Comment by themilkman** [comment]
I just created a PR regarding this that you might be interested to try :)

**Comment by mathieujobin** [comment]
see #741 as well
