### ISSUE TITLE
`Errno::EACCES: Permission denied` when attempting to install on Windows

### ISSUE THREAD

**Issue by Bodacious** [Apipie/apipie-rails#704]
Hi all,

Attempting to install version `0.5.18` on Windows 10 and I'm getting the following permissions error.

```
Errno::EACCES: Permission denied @ rb_file_s_symlink - (./Gemfile.rails50,
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/apipie-rails-0.5.18/Gemfile)
An error occurred while installing apipie-rails (0.5.18), and
Bundler cannot continue.
Make sure that `gem install apipie-rails -v '0.5.18' --source
'https://rubygems.org/'` succeeds before bundling.
```

The error even happens when installing the bundle to `./vendor/bundle`, which we have full permissions for.

This seems to be caused by the Gemfile, which is a symlink and not a regular file. 

I'm not a regular Windows user (helping a colleague with his setup) and I'm a bit lost at how to approach fixing this.

cc: @angelivanovvv

**Comment by jirubio** [comment]
@mathieujobin this is fixed since 0.7.1
