### ISSUE TITLE
Security vulnerability with bootstrap

### ISSUE THREAD

**Issue by waissbluth** [Apipie/apipie-rails#707]
The version of bootstrap (v2.0.2) [included with this package](https://github.com/Apipie/apipie-rails/blob/master/app/public/apipie/javascripts/bundled/bootstrap.js) is subject to [several XSS security vulnerabilities](https://snyk.io/vuln/npm:bootstrap).

I suggest upgrading to [v2.3.2](https://getbootstrap.com/2.3.2/), which is the latest 2.x.x release, but it would be nice if the dependency was somehow linked instead of directly copied into this repository. 

This also applies to the component [bootstrap-collapse](https://github.com/Apipie/apipie-rails/blob/master/app/public/apipie/javascripts/bundled/bootstrap-collapse.js).

**Comment by mathieujobin** [comment]
Thanks for the PR ! This is highly valuable

**Comment by davidwessman** [comment]
@mathieujobin This can be closed right?
