### ISSUE TITLE
array_of property is always required (ignoring required: false)

### ISSUE THREAD

**Issue by jankmet** [Apipie/apipie-rails#709]
```
def_param_group :Item do
  property :id, :number
  property :name, String
  property :description, String, required: false
  property :referenced_ids, array_of: :number, required: false
end
```

description is optional, but referenced_ids is required (apipie, swagger)

**Comment by ghillahill** [comment]
I have the same issue, setting the property to required: false, but I get required true in the swagger. Any update?

**Comment by PanosCodes** [comment]
@ghillahill could you test https://github.com/Apipie/apipie-rails/pull/863 ?

**Comment by ghillahill** [comment]
@PanosCodes works fine. Thank you.
