### ISSUE TITLE
Feature request: Export to OpenAPI 3.0

### ISSUE THREAD

**Issue by oliver-hohn** [Apipie/apipie-rails#713]
Thank you for maintaining and contributing to the project! This is a great library for documenting APIs alongside the controller code :+1:

Based on the `README`, this gem supports exporting to OpenAPI v2.0 but not v3.0. Are there plans to support exporting to OpenAPI v3.0 in the near future?

**Comment by fskale** [comment]
Did you try to export the api in swagger format ?
Anyhow, the swagger output lacks of the response format attributes.
When examining the swagger output e.g for task/:id the response is.

Give it a try:
`foreman-rake apipie:static_swagger_json`

What is missing is the response item format. Like:
`
"content": {
 "application/json": {
  "schema": {
    "type": "object",
    "properties": {
      "pets": {
        "type": "array",
        "items": {
          "type": "object"
        }
      }
    }
  }
}
`

Input validation is crucial though.


Rgds.
Franz

**Comment by fskale** [comment]
Nevertheless it would be great to have a swagger v2.0 compatible export function which will cover the response objects too. ($ref)
It's OpenApi 3.0 compatible, any OpenApi 3.0 tool will be able to convert the swagger v2.0 output.

**Comment by mathieujobin** [comment]
Swagger v2.0 should be working in v1.x please test.

**Comment by epugh** [comment]
Does this mean we are already OpenAPI 3 compatible?

**Comment by mathieujobin** [comment]
Yes, as far as I know we are OpenAPI 3.0 compliant, maybe it was a mistake to use Swagger in our naming. But its quite common in various implementation.

https://swagger.io/blog/api-strategy/difference-between-swagger-and-openapi/
https://apidog.com/blog/swagger-vs-openapi/

Please do try the latest version and let us know if anything is incorrect or incomplete.

**Comment by mathieujobin** [comment]
PRs to improve on the documentation, the code base or the test suite are very welcome.

**Comment by mathieujobin** [comment]
some issues I label them as "Question" and keep open, as I find them more useful open than close.

**Comment by epugh** [comment]
Cool..    BTW https://github.com/o19s/quepid/pull/808 and I was able to export the swagger/oauth 2.0 formatted file, and then upload it to https://github.com/Redocly/redoc and parse it!

**Comment by mathieujobin** [comment]
Awesome, big thanks to @PanosCodes for making this a reality. 
Happy to hear it works for you.
