### ISSUE TITLE
Prepping next releases

### ISSUE THREAD

**Issue by mathieujobin** [Apipie/apipie-rails#745]
... continuing conversations from #743 

@ofedoren @themilkman I would release current master as 0.6.0 as it only constains ruby 3 fixes and the removal of unnecessary dependencies.

https://github.com/Apipie/apipie-rails/pull/737 could go along if all tests pass, or in 0.6.1

I am curious to understand the issue that https://github.com/Apipie/apipie-rails/pull/744 fixes
but if all tests pass, it seems harmless to include soon.

similar with https://github.com/Apipie/apipie-rails/pull/732

this bug fix rings a bell... https://github.com/Apipie/apipie-rails/pull/733
but 3 tests are failing on rails 4.2
so this would go into 1.0 where I would remove support for `< 5.2`
unless the author figure out the tests

**Comment by themilkman** [comment]
Hi @mathieujobin , 

I just tested against master@85aa3b5 and it works for me in a rails 7 env. Thanks!

Those Rails 4.2 problems are really strange... I won't be sad once those are dropped from the test matrix.
Talking about the test matrix - I'll try to make a PR for rails 7 in order to get this more complete.

Generally: LGTM!

**Comment by ofedoren** [comment]
0.6.0 with Ruby 3 fixes only sound just fine, yeah.

I'm okay with dropping Rails 4 support, it's really quite old and probably not supported anymore :/

BTW, @mathieujobin, do you want rubygems perms, so you're able to create gems or you want me to create them after you've pushed the tags here? I somehow missed that...

**Comment by mathieujobin** [comment]
Yes I can build and push directly if you give me access.

https://rubygems.org/profiles/mathieu

Is my profile. I think you can invite by username?

`gem owner ph_model --add mathieu` <-- :pray: 

Otherwise I would like to give you my email privately...

**Comment by ofedoren** [comment]
> Is my profile. I think you can invite by username?

I've sent the invite :)

**Comment by themilkman** [comment]
@mathieujobin I won't have time for the mentioned rails 7 thingy as it didn't work as smooth as I expected yesterday and I don't understand the error yet.
From my personal side side, I'd say: Release the kraken :)

**Comment by mathieujobin** [comment]
I will soon

**Comment by mathieujobin** [comment]
updated changelog and bump version for next release 5b925fc9b36160c4c4ddead0ff177d193653f734

**Comment by mathieujobin** [comment]
next inline for review @themilkman @ofedoren 

https://github.com/Apipie/apipie-rails/pull/747

I can release tomorrow

**Comment by mathieujobin** [comment]
We're good for now

**Comment by mathieujobin** [comment]
Actually, this is what I am thinking to include next
https://github.com/Apipie/apipie-rails/pull/708

I could bump to 0.8.0 as it fix a security issue and potentially has visual changes.

opinion?

**Comment by ofedoren** [comment]
I'm okay with that, maybe we could even CP it to the stable and release 0.5.21 since it's a security fix. My only concern is if the license is the same (probably it is, just to be sure)

**Comment by themilkman** [comment]
Couldn't try the PR ATM (will try to locally build with the PR and do a quick optical compare later) but I checked the license headers in the diffs - they didn't change.

**Comment by themilkman** [comment]
In my docs I could observe minor visible differences using a rebased PR branch of #708 but generally it looked even better. Nothing seems to be broken so I think it is fine. :+1:

**Comment by ofedoren** [comment]
> In my docs I could observe minor visible differences using a rebased PR branch of #708 but generally it looked even better. Nothing seems to be broken so I think it is fine. +1

Thanks for testing that out! I know it's a bit much to ask, but could you provide screenshot of what have changed, just so more people are aware?

**Comment by mathieujobin** [comment]
This is great help @themilkman 
This would go into 0.8.0, I could cherry-pick into stable for 0.5.21 but at the same time, I'd rather wait until there is demands for it... 
there is one open bug against 0.7.0 right now, but otherwise, it could be all considered stable soon.
Giving it a few more months, though.

**Comment by themilkman** [comment]
Hi, sorry, a bit busy but just found a few minutes for a quick optical impression what has changed:
Old:
![pie_old](https://user-images.githubusercontent.com/1582492/161750023-6f8d27fb-ea78-40da-9b68-1bd6da5af919.png)
New:
![pie_new](https://user-images.githubusercontent.com/1582492/161750032-706d0554-6509-4157-85a8-a92453b458d9.png)
So stuff got bigger, gradient is gone and the "current" breadcrumb has a different color (as well as being blue when on the root). That's at least here on Firefox with a pull --rebase against master.

**Comment by mathieujobin** [comment]
opinions on #691 ?

**Comment by mathieujobin** [comment]
I'm looking at https://github.com/Apipie/apipie-rails/pull/689
Many positive votes towards it...

@ofedoren I think you have the ability to resolve the conflict on open PR.
Can I get that ability?
