### ISSUE TITLE
[Warning] Skipping set of ruby2_keywords flag for process (method accepts keywords or method does not accept argument splat)

### ISSUE THREAD

**Issue by jsantos** [Apipie/apipie-rails#753]
After updating to 0.6.0, I keep getting the following warning: 

```
.../.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/apipie-rails-0.7.1/lib/apipie/extractor/recorder.rb:163: warning: Skipping set of ruby2_keywords flag for process (method accepts keywords or method does not accept argument splat)
```

It seems to have been introduced on #716.

This seems to be the problem: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/.

I'm just not sure how to fix it. If anyone has advice on this, I can test it out and create a PR.

**Comment by mathieujobin** [comment]
Honestly, I also don't quite understand why or if it is at all required...
but removing it appears to not cause any problem on my end...

feel free to try out this branch if you want

https://github.com/Apipie/apipie-rails/pull/754

`gem 'apipie-rails', github: 'Apipie/apipie-rails', branch: 'remove-ruby2_keywords'`
