### ISSUE TITLE
[Feature request] Remove default tags from generated swagger json

### ISSUE THREAD

**Issue by vinczedani** [Apipie/apipie-rails#759]
Hello
When using swagger ui with the swagger json generated by apipie. The jsons always contain a default tag (the controller name or path) even if I specify tags in the resource_description, or give the resource a unique name, this results in multiple occurrences of the same endpoint on the swagger ui. Can I somehow get rid of the tag that was not given by me?
Thank you!

If I read the code properly, currently it is always there currently https://github.com/Apipie/apipie-rails/blob/master/lib/apipie/swagger_generator.rb#L229

**Comment by mathieujobin** [comment]
I don't personally use the Swagger features, so I am not too familiar with these tags.
But we could wrap those default tags in a configuration setting flag.
So it can be turned off.

Reviewing the changes done in https://github.com/Apipie/apipie-rails/pull/634

If you have the time to prepare a PR and all tests pass, I'll review. The main point is we want to remain backward compatible.

**Comment by davidwessman** [comment]
https://github.com/Apipie/apipie-rails/pull/881
I took a swing at fixing this, please check it out - open to any feedback!
