### ISSUE TITLE
Report all missing required parameters instead of just the first

### ISSUE THREAD

**Issue by twopoint718** [Apipie/apipie-rails#802]
In the case of an endpoint having multiple required params, would it be possible to include all missing params in the error message? As it is, it looks like these are reported one-by-one in order:

https://github.com/Apipie/apipie-rails/blob/6a0174d20d3ccfe9a0a528826eb4abe886728021/lib/apipie/dsl_definition.rb#L246-L251

**Comment by mathieujobin** [comment]
That would be a great enhancement indeed.

Are you able to open a pull request with the fix? and ideally a test that ensure we don't break this in the future?
