### ISSUE TITLE
Generate multiple swagger-files

### ISSUE THREAD

**Issue by davidwessman** [Apipie/apipie-rails#887]
We have the need for generating multiple swagger files as output from `apipie`.

We might have different versions and different namespaces that we want to be separate swagger files.

`api/v1/namespace_a` => `/swagger/v1/namespace_a/swagger.yaml` 
`api/v2/namespace_a`=> `/swagger/v2/namespace_a/swagger.yaml`
`api/v1/namespace_b`=> `/swagger/v1/namespace_b/swagger.yaml`

I am open to working on this with a colleague, but would be great with some pointers on how to start.
Almost feels like we need to do some breaking changes in the swagger config to make this work.

I am also open to be able to pass it as arguments to the CLI:
```sh
bundle exec rails apipie:static_swagger_json --output /swagger/v1/namespace_a/swagger.yaml --paths "app/controllers/v1/namespace_a/**/*.rb"
bundle exec rails apipie:static_swagger_json --output /swagger/v2/namespace_a/swagger.yaml --paths "app/controllers/v2/namespace_a/**/*.rb"
bundle exec rails apipie:static_swagger_json --output /swagger/v1/namespace_b/swagger.yaml --paths "app/controllers/v1/namespace_b/**/*.rb"
```

**Comment by davidwessman** [comment]
I will investigate it more tomorrow 🙂 
But then it feels like it would be easiest to fix by handling it via rake-commands instead of the config?

**Comment by PanosCodes** [comment]
Correct, I don't think the configuration is the right place for that.

**Comment by davidwessman** [comment]
@PanosCodes It seems like no matter which version I generate, they all end up in the same file and overwrite each other.
Am I missing some configuration?

**Comment by davidwessman** [comment]
Decided to add my namespace to the version and use the `ENV["OUT"]`:
```
OUT=./swagger/v1/namespace_a bundle exec rails apipie:static_swagger_json\[1\.namespace\_a\]
OUT=./swagger/v1/namespace_b bundle exec rails apipie:static_swagger_json\[1\.namespace\_b\]
```

**Comment by mathieujobin** [comment]
Thanks for the update
