### ISSUE TITLE
How do I specify a custom Description, I get "Another API description"

### ISSUE THREAD

**Issue by epugh** [Apipie/apipie-rails#899]
I've got a default "Another API description", I expected to put something in `/config/initializers/apipie.rb`!

**Comment by PanosCodes** [comment]
You are correct !!!
Have you tried setting up the [app_info](https://github.com/Apipie/apipie-rails#configuration-reference) config option in in `/config/initializers/apipie.rb`

```ruby
Apipie.configure do |config|
  # ....
  config.app_info = 'An awesome description 🚀'
  # ....
end
```

**Comment by epugh** [comment]
Thank you!
