### ISSUE TITLE
How to display an example for a request in Swagger?

### ISSUE THREAD

**Issue by ekuzovlev** [Apipie/apipie-rails#922]
Swagger has a requestBody field that allows displaying an example for the request. 
How can this be specified in Apipie?

```
 requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order
```
<img width="707" alt="image" src="https://github.com/Apipie/apipie-rails/assets/78175102/110dc12b-04ce-4a57-b1b0-510618c1bfeb">

**Comment by PanosCodes** [comment]
I believe you can't. It looks like a [known limitation](https://github.com/Apipie/apipie-rails?tab=readme-ov-file#known-limitations-of-the-current-implementation)
